// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QuizBasicInfoAddedToQuizPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuizBasicInfoAddedToQuizPage));
        
        string IMigrationMetadata.Id
        {
            get { return "202104052253450_QuizBasicInfoAddedToQuizPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
